## Sentiment based on neighbours

0. knn result:
    - finding x nearest neighbours
    - taking the ones that are above a similarity threshold
    - taking the mean

1. Internal evaluation:
    - for each word (embedding) in sentida2:
        - compare knn result to true sentiment score
        
2. Predict for jørg embeddings:
    - lexicon evaluation

In [119]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsRegressor, NearestNeighbors
from sklearn.metrics import mean_absolute_error

In [44]:
X = np.load("../../data/training_data/X_w2v_asent.npy")
y = np.load("../../data/training_data/y_w2v_asent.npy")
y_reshaped= y.reshape([6420,1])

numpy.ndarray

TypeError: unhashable type: 'numpy.ndarray'

In [50]:
y_reshaped

array([[-1.        ],
       [-0.33333333],
       [ 0.33333333],
       ...,
       [-1.        ],
       [-2.        ],
       [-3.        ]])

In [103]:
neigh = KNeighborsRegressor(n_neighbors=5, weights="distance")
neigh.fit(X, y_reshaped)
y_predictions = neigh.predict(X)
print(mean_absolute_error(y_reshaped, y_predictions))

0.0


In [108]:
X_to_predict = np.load("../../data/prediction_data/w2v_embeds_to_predict.npy")
words_to_predict =np.load("../../data/prediction_data/w2v_words_to_predict.npy")

In [142]:
neigh = KNeighborsRegressor(n_neighbors=20, weights="distance")
neigh.fit(X, y_reshaped)
y_predictions = neigh.predict(X_to_predict)

In [143]:
y_preds = [y[0] for y in y_predictions]

In [144]:
df = pd.DataFrame(list(zip(words_to_predict, y_preds)), columns=["word", "score"])

In [145]:
df

word     score
0          slankekur -0.986416
1              falme  0.199381
2         smørrebrød  0.894701
3            øjekast -1.038895
4               vals -0.554218
...              ...       ...
8634    klarinettist  0.356136
8635          jovist -0.592078
8636     gennemprøve -0.475519
8637  brændselscelle -1.146147
8638   møbelarkitekt -0.758248

[8639 rows x 2 columns]

In [146]:
df.to_csv("../../output/knn_predictions_word2vec.csv")

In [95]:
nbrs = NearestNeighbors(n_neighbors=8).fit(X)
distances, indices = nbrs.kneighbors(X)

predictions=[]
for i in range(0,6420):
    idxs = indices[i]   
    score1=y_reshaped[idxs[1]]
    score2=y_reshaped[idxs[2]]
    score3=y_reshaped[idxs[3]]
    score4=y_reshaped[idxs[4]]
    score5=y_reshaped[idxs[5]]
    score6=y_reshaped[idxs[6]]
    score7=y_reshaped[idxs[7]]
    predicted = (sum([score1, score2, score3, score4, score5, score6, score7])/7)
    predictions.append(predicted)

In [96]:
predictions[0]

array([-4.0952381])

In [97]:
y_reshaped[0]

array([-1.])

In [98]:
mean_absolute_error(y_reshaped, predictions)

0.9591208030460369